name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Run Build"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore 

    - name: Publish ImpfTerminBot.Forms
      if: ${{ always() }}
      run: dotnet publish ${{ github.workspace }}/ImpfTerminBot.Forms.csproj --configuration Release 
      
    - name: Upload ImpfTerminBot.Forms Build Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ImpfTerminBot.Forms
        path: /${{ github.workspace }}/ImpfTerminBot.Forms.csproj/bin/Release/netcoreapp3.1/publish/      
      


    
