name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Run Build"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore 

    - name: Publish ImpfTerminBot.GUI
      if: ${{ always() }}
      run: dotnet publish ${{ github.workspace }}/ImpfTerminBot.GUI/ImpfTerminBot.GUI.csproj --configuration Release 

    - name: Upload ImpfTerminBot.GUI Build Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ImpfTerminBot.GUI
        path: ${{ github.workspace }}/ImpfTerminBot.GUI/bin/Release/netcoreapp3.1/publish/
        
    - name: Zip Files
      run: Compress-Archive ${{ github.workspace }}/ImpfTerminBot.GUI/bin/Release/netcoreapp3.1/publish/*.* ImpfTerminBot.zip
        
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "ImpfTerminBot Release"
        files: ImpfTerminBot.zip
